# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/code/anoki

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/code/anoki

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/code/anoki/CMakeFiles /Users/code/anoki//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/code/anoki/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/code/anoki/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rings-beamformer

# Build rule for target.
rings-beamformer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rings-beamformer
.PHONY : rings-beamformer

# fast build rule for target.
rings-beamformer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/build
.PHONY : rings-beamformer/fast

#=============================================================================
# Target rules for targets named STM32_Drivers

# Build rule for target.
STM32_Drivers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 STM32_Drivers
.PHONY : STM32_Drivers

# fast build rule for target.
STM32_Drivers/fast:
	$(MAKE) $(MAKESILENT) -f cmake/stm32cubemx/CMakeFiles/STM32_Drivers.dir/build.make cmake/stm32cubemx/CMakeFiles/STM32_Drivers.dir/build
.PHONY : STM32_Drivers/fast

App/Src/awmf210.obj: App/Src/awmf210.c.obj
.PHONY : App/Src/awmf210.obj

# target to build an object file
App/Src/awmf210.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/App/Src/awmf210.c.obj
.PHONY : App/Src/awmf210.c.obj

App/Src/awmf210.i: App/Src/awmf210.c.i
.PHONY : App/Src/awmf210.i

# target to preprocess a source file
App/Src/awmf210.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/App/Src/awmf210.c.i
.PHONY : App/Src/awmf210.c.i

App/Src/awmf210.s: App/Src/awmf210.c.s
.PHONY : App/Src/awmf210.s

# target to generate assembly for a file
App/Src/awmf210.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/App/Src/awmf210.c.s
.PHONY : App/Src/awmf210.c.s

App/Src/laura.obj: App/Src/laura.c.obj
.PHONY : App/Src/laura.obj

# target to build an object file
App/Src/laura.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/App/Src/laura.c.obj
.PHONY : App/Src/laura.c.obj

App/Src/laura.i: App/Src/laura.c.i
.PHONY : App/Src/laura.i

# target to preprocess a source file
App/Src/laura.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/App/Src/laura.c.i
.PHONY : App/Src/laura.c.i

App/Src/laura.s: App/Src/laura.c.s
.PHONY : App/Src/laura.s

# target to generate assembly for a file
App/Src/laura.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/App/Src/laura.c.s
.PHONY : App/Src/laura.c.s

App/Src/soham.obj: App/Src/soham.c.obj
.PHONY : App/Src/soham.obj

# target to build an object file
App/Src/soham.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/App/Src/soham.c.obj
.PHONY : App/Src/soham.c.obj

App/Src/soham.i: App/Src/soham.c.i
.PHONY : App/Src/soham.i

# target to preprocess a source file
App/Src/soham.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/App/Src/soham.c.i
.PHONY : App/Src/soham.c.i

App/Src/soham.s: App/Src/soham.c.s
.PHONY : App/Src/soham.s

# target to generate assembly for a file
App/Src/soham.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/App/Src/soham.c.s
.PHONY : App/Src/soham.c.s

App/Src/usb-spi-control.obj: App/Src/usb-spi-control.c.obj
.PHONY : App/Src/usb-spi-control.obj

# target to build an object file
App/Src/usb-spi-control.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/App/Src/usb-spi-control.c.obj
.PHONY : App/Src/usb-spi-control.c.obj

App/Src/usb-spi-control.i: App/Src/usb-spi-control.c.i
.PHONY : App/Src/usb-spi-control.i

# target to preprocess a source file
App/Src/usb-spi-control.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/App/Src/usb-spi-control.c.i
.PHONY : App/Src/usb-spi-control.c.i

App/Src/usb-spi-control.s: App/Src/usb-spi-control.c.s
.PHONY : App/Src/usb-spi-control.s

# target to generate assembly for a file
App/Src/usb-spi-control.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/App/Src/usb-spi-control.c.s
.PHONY : App/Src/usb-spi-control.c.s

Core/Src/main.obj: Core/Src/main.c.obj
.PHONY : Core/Src/main.obj

# target to build an object file
Core/Src/main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/Core/Src/main.c.obj
.PHONY : Core/Src/main.c.obj

Core/Src/main.i: Core/Src/main.c.i
.PHONY : Core/Src/main.i

# target to preprocess a source file
Core/Src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/Core/Src/main.c.i
.PHONY : Core/Src/main.c.i

Core/Src/main.s: Core/Src/main.c.s
.PHONY : Core/Src/main.s

# target to generate assembly for a file
Core/Src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/Core/Src/main.c.s
.PHONY : Core/Src/main.c.s

Core/Src/stm32u5xx_hal_msp.obj: Core/Src/stm32u5xx_hal_msp.c.obj
.PHONY : Core/Src/stm32u5xx_hal_msp.obj

# target to build an object file
Core/Src/stm32u5xx_hal_msp.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/Core/Src/stm32u5xx_hal_msp.c.obj
.PHONY : Core/Src/stm32u5xx_hal_msp.c.obj

Core/Src/stm32u5xx_hal_msp.i: Core/Src/stm32u5xx_hal_msp.c.i
.PHONY : Core/Src/stm32u5xx_hal_msp.i

# target to preprocess a source file
Core/Src/stm32u5xx_hal_msp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/Core/Src/stm32u5xx_hal_msp.c.i
.PHONY : Core/Src/stm32u5xx_hal_msp.c.i

Core/Src/stm32u5xx_hal_msp.s: Core/Src/stm32u5xx_hal_msp.c.s
.PHONY : Core/Src/stm32u5xx_hal_msp.s

# target to generate assembly for a file
Core/Src/stm32u5xx_hal_msp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/Core/Src/stm32u5xx_hal_msp.c.s
.PHONY : Core/Src/stm32u5xx_hal_msp.c.s

Core/Src/stm32u5xx_it.obj: Core/Src/stm32u5xx_it.c.obj
.PHONY : Core/Src/stm32u5xx_it.obj

# target to build an object file
Core/Src/stm32u5xx_it.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/Core/Src/stm32u5xx_it.c.obj
.PHONY : Core/Src/stm32u5xx_it.c.obj

Core/Src/stm32u5xx_it.i: Core/Src/stm32u5xx_it.c.i
.PHONY : Core/Src/stm32u5xx_it.i

# target to preprocess a source file
Core/Src/stm32u5xx_it.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/Core/Src/stm32u5xx_it.c.i
.PHONY : Core/Src/stm32u5xx_it.c.i

Core/Src/stm32u5xx_it.s: Core/Src/stm32u5xx_it.c.s
.PHONY : Core/Src/stm32u5xx_it.s

# target to generate assembly for a file
Core/Src/stm32u5xx_it.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/Core/Src/stm32u5xx_it.c.s
.PHONY : Core/Src/stm32u5xx_it.c.s

Core/Src/syscalls.obj: Core/Src/syscalls.c.obj
.PHONY : Core/Src/syscalls.obj

# target to build an object file
Core/Src/syscalls.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/Core/Src/syscalls.c.obj
.PHONY : Core/Src/syscalls.c.obj

Core/Src/syscalls.i: Core/Src/syscalls.c.i
.PHONY : Core/Src/syscalls.i

# target to preprocess a source file
Core/Src/syscalls.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/Core/Src/syscalls.c.i
.PHONY : Core/Src/syscalls.c.i

Core/Src/syscalls.s: Core/Src/syscalls.c.s
.PHONY : Core/Src/syscalls.s

# target to generate assembly for a file
Core/Src/syscalls.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/Core/Src/syscalls.c.s
.PHONY : Core/Src/syscalls.c.s

Core/Src/sysmem.obj: Core/Src/sysmem.c.obj
.PHONY : Core/Src/sysmem.obj

# target to build an object file
Core/Src/sysmem.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/Core/Src/sysmem.c.obj
.PHONY : Core/Src/sysmem.c.obj

Core/Src/sysmem.i: Core/Src/sysmem.c.i
.PHONY : Core/Src/sysmem.i

# target to preprocess a source file
Core/Src/sysmem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/Core/Src/sysmem.c.i
.PHONY : Core/Src/sysmem.c.i

Core/Src/sysmem.s: Core/Src/sysmem.c.s
.PHONY : Core/Src/sysmem.s

# target to generate assembly for a file
Core/Src/sysmem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/Core/Src/sysmem.c.s
.PHONY : Core/Src/sysmem.c.s

startup_stm32u575xx.obj: startup_stm32u575xx.s.obj
.PHONY : startup_stm32u575xx.obj

# target to build an object file
startup_stm32u575xx.s.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rings-beamformer.dir/build.make CMakeFiles/rings-beamformer.dir/startup_stm32u575xx.s.obj
.PHONY : startup_stm32u575xx.s.obj

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... STM32_Drivers"
	@echo "... rings-beamformer"
	@echo "... App/Src/awmf210.obj"
	@echo "... App/Src/awmf210.i"
	@echo "... App/Src/awmf210.s"
	@echo "... App/Src/laura.obj"
	@echo "... App/Src/laura.i"
	@echo "... App/Src/laura.s"
	@echo "... App/Src/soham.obj"
	@echo "... App/Src/soham.i"
	@echo "... App/Src/soham.s"
	@echo "... App/Src/usb-spi-control.obj"
	@echo "... App/Src/usb-spi-control.i"
	@echo "... App/Src/usb-spi-control.s"
	@echo "... Core/Src/main.obj"
	@echo "... Core/Src/main.i"
	@echo "... Core/Src/main.s"
	@echo "... Core/Src/stm32u5xx_hal_msp.obj"
	@echo "... Core/Src/stm32u5xx_hal_msp.i"
	@echo "... Core/Src/stm32u5xx_hal_msp.s"
	@echo "... Core/Src/stm32u5xx_it.obj"
	@echo "... Core/Src/stm32u5xx_it.i"
	@echo "... Core/Src/stm32u5xx_it.s"
	@echo "... Core/Src/syscalls.obj"
	@echo "... Core/Src/syscalls.i"
	@echo "... Core/Src/syscalls.s"
	@echo "... Core/Src/sysmem.obj"
	@echo "... Core/Src/sysmem.i"
	@echo "... Core/Src/sysmem.s"
	@echo "... startup_stm32u575xx.obj"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/code/anoki/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

